export const  FETCH_RECRUIT_DATA = "FETCH_RECRUIT_DATA";
export const  FETCH_RECRUIT_FAILED = "FETCH_RECRUIT_FAILED";
export const  FETCH_RECRUIT_SUCCESS = "FETCH_RECRUIT_SUCCESS";

export const SET_RECRUIT_PAGE = "SET_RECRUIT_PAGE"
export const SET_RECRUIT_PAGE_SIZE = "SET_RECRUIT_PAGE_SIZE"