export const ListRecruitmentModel = [

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},
]

export const MyRecruitedModel = [

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "pending",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "accepted",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},

	{
		name: "Tuyển dụng nhân viên kiểm thử",
		description: "Tuyển dụng nhân viên kiểm thử",
		creator: "Nguyễn Thế Lữ",
		dateStart: "20/11/2020",
		dateEnd: "20/11/2020",
		count: 2,
		status: "rejected",
		type: "0",
		position: "1",
		files: "Danh sách file đính kèm",
	},
]