export const FETCH_JOB_DATA = "FETCH_JOB_DATA"
export const FETCH_JOB_FAILED = "FETCH_JOB_FAILED"
export const FETCH_JOB_SUCCESS = "FETCH_JOB_SUCCESS"

export const FETCH_JOB_DETAIL = "FETCH_JOB_DETAIL"
export const FETCH_JOB_DETAIL_FAILED = "FETCH_JOB_DETAIL_FAILED"
export const FETCH_JOB_DETAIL_SUCCESS = "FETCH_JOB_DETAIL_SUCCESS"

export const SET_JOB_PAGE = "SET_JOB_PAGE"
export const SET_JOB_PAGE_SIZE = "SET_JOB_PAGE_SIZE"