export const  FETCH_MY_RECRUIT_DATA = "FETCH_MY_RECRUIT_DATA";
export const  FETCH_MY_RECRUIT_FAILED = "FETCH_MY_RECRUIT_FAILED";
export const  FETCH_MY_RECRUIT_SUCCESS = "FETCH_MY_RECRUIT_SUCCESS";

export const SET_MY_RECRUIT_PAGE = "SET_MY_RECRUIT_PAGE"
export const SET_MY_RECRUIT_PAGE_SIZE = "SET_MY_RECRUIT_PAGE_SIZE"